"""add two receipt columns

Revision ID: d2f5da82c720
Revises: d93d30cada5b
Create Date: 2025-09-22 17:41:18.395211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f5da82c720'
down_revision = 'd93d30cada5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_filename1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('receipt_filename2', sa.String(length=255), nullable=True))
        batch_op.drop_column('receipt_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('receipt_filename2')
        batch_op.drop_column('receipt_filename1')

    # ### end Alembic commands ###
